version: "3"
services:
  front:
    build:
      context: .
    container_name: mocean_local
    environment:
      TZ: Asia/Seoul
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"