
version: "3"
services:
  front:
    build:
      context: .
    restart: always
    container_name: mocean_front
    environment:
      TZ: Asia/Seoul
      VIRTUAL_HOST: www.moceancrm.com, moceancrm.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: www.moceancrm.com, moceancrm.com
    networks:
      - nginx-proxy
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
networks:
  nginx-proxy:
    external: true